# This is a basic workflow to help you get started with Actions

name: demo
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  demo:
    runs-on: ubuntu-latest
    envornment: PROD
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello!
      - name: Try print Env Secret
        run: ${{ secrets.GPG_KEY }}
